### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by ghost** [VasylPosmit/health#22]
Hello, I am struggling to launch the application. Can you include a tutorial? (I am launching on localhost)

**Comment by VasylPosmit** [comment]
First, check  node, npm and bower versions

```
node -v         //  v  5.3.0 +   should work
npm -v          //  v  3.3.12 + should work
bower -v        //  v 1.7.7 +    should work

```

Next [clon the repository
](https://help.github.com/articles/cloning-a-repository/)
Then, from root directory in console (Git Bash for example)

```
npm install
bower install
gulp                // to make build

gulp serve         // should launch localhost 
or
gulp serve:dist // should launch localhost form dist folder 

```
